/**
 * room_data.h — Auto-generated by tools/parse_room/convert_quadtree.py
 */
#ifndef ROOM_DATA_H
#define ROOM_DATA_H

#include <stdint.h>
#include "../../../types.h"

typedef struct {
    float            x_mm;
    float            y_mm;
    semantic_class_t cls;
} room_point_t;

extern const room_point_t ROOM_DATA[];
extern const uint32_t     ROOM_DATA_COUNT;
extern const float        ROOM_WIDTH_MM;
extern const float        ROOM_HEIGHT_MM;
extern const pose_t       ROOM_START_POSE;

#endif /* ROOM_DATA_H */
