/**
 * room_waypoints.h
 * Auto-generated by tools/parse_room/generate_lidar_map.py — do not edit.
 * Waypoint sequence derived from room.log (Carmen GFS / FLASER, stride=5).
 *
 * Coordinate frame: ESP32 dead-reckoning starts at
 *   (5000, 5000) mm  ≡  first room.log pose (2.048, -0.316) m
 * Matches the espStartX / espStartY fields in tools/dashboard/room_map_data.js.
 */

#ifndef ROOM_WAYPOINTS_H
#define ROOM_WAYPOINTS_H

#include <stdint.h>
#include "../../../types.h"

/** Total number of waypoints. */
extern const uint16_t ROOM_WAYPOINT_COUNT;

/** room.log scan index each waypoint was sampled from.
 *  Broadcast as "si" over WebSocket so the browser advances the map render. */
extern const uint16_t ROOM_WAYPOINT_SCAN_IDX[72];

/** Waypoint sequence in ESP32 mm dead-reckoning frame. */
extern const waypoint_t ROOM_WAYPOINTS[72];

/** Starting pose — initialise pose_t from this in app_main. */
extern const pose_t ROOM_WP_START_POSE;

#endif /* ROOM_WAYPOINTS_H */
