// Auto-generated by tools/parse_room/generate_lidar_map.py
// Source: room.log  —  do not edit manually.

const ROOM_MAP_META = {
  imageFile:  'lidar_map.png',
  pxPerMeter: 20.0,
  cellMm:     50.0,   // mm per pixel (50 mm = 5 cm)
  originX:    -6.8990540973396275,     // world x at image left edge   (metres)
  originY:    -18.05108931621242,     // world y at image bottom edge (metres)
  widthPx:    483,
  heightPx:   478,
  gridCols:   483,      // alias used by coordinate helpers
  gridRows:   478,
  startX:     2048.0,   // world position of robot start (mm)
  startY:     -316.0,
  startTheta: -0.340462,
  // ESP32 dead-reckoning starts at (espStartX, espStartY) mm = (startX, startY) world mm.
  espStartX:  5000.0,
  espStartY:  5000.0,
};

// No ROOM_WALL_CELLS / ROOM_FREE_CELLS — map loaded from lidar_map.png.
const ROOM_WALL_CELLS = [];
const ROOM_FREE_CELLS = [];
